### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by jkrzefski** [ptcong/easyrequest#1]
I always get this error when I try to require this:

[InvalidArgumentException] Could not find package ^1.0 at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by ptcong** [comment]
try `^1.0.0` or `~1.0.0`

**Comment by jkrzefski** [comment]
Still get the same error. I even changed my minimum-stability to dev but it still doesn't find anything.

**Comment by ptcong** [comment]
What's your composer version ?
could you provide full your composer.json file ?

i've tried with this 
```
{
    "require": {
        "ptcong/easyrequest": "^1.0"
    }
}
```
it works fine.

**Comment by jkrzefski** [comment]
Well, I don't know why, but requiring the package via the composer.json-file works. Requiring it via the command you provided in your readme does not. That (for me) even is the case on a blank composer.json-file. At least it works now. Thank you for your help.
