### ISSUE TITLE
withHeader() seems not to exist

### ISSUE THREAD

**Issue by splitbrain** [ptcong/easyrequest#10]
The docs mention a withHeader() method which would make sense to me as it would be analog to the other with* methods. But it seems that method does not exist?

**Comment by shtse8** [comment]
https://github.com/ptcong/easyrequest/blob/59b6bfa1620bdcbb82c7b7deb50e671572633653/src/Psr7/Message.php#L159

This method is in the `Message`, and the `Request` extends `Message`. So you can call this method with all `Request` Object.

**Comment by splitbrain** [comment]
weird. my IDE wasn't picking it up. must be an error on my side. sorry for the noise.
