### ISSUE TITLE
Calling getResponse() should always return a Response.

### ISSUE THREAD

**Issue by shtse8** [ptcong/easyrequest#5]
As the method name getResponse, this method should always return a Response.
We also can benefit from calling chain method after that.

For example:
```
$request = Client::request('https://www.domain.com/');
$request->send();
$body = $request->getResponse()->getBody();
```

Once getResponse return null, the following error will be thrown:
```
Call to a member function getBody() on null
```

So do you think changing getResponse should always return a Response Object even there is no Response?

```
public function getResponse()
    {
        return $this->responses ? end($this->responses) : null;
    }
```
Changes to
```
public function getResponse()
    {
        return $this->responses ? end($this->responses) : new \EasyRequest\Psr7\Response;
    }
```

**Comment by ptcong** [comment]
What you think with this code
```
$response = $request->send();
$body = $response ? $response->getBody() : null;
```
or 
```
$response = $request->send();
if (response) {
 // make sure request is sent successful and got response 
}
```

**Comment by shtse8** [comment]
because developers want to get direct body from requests in most cases. so
I think simplifying getbody is a good idea. in order to write serveral
lines to get a body from a request, make it into one line seems better.

2016年12月4日 上午9:30，"Phan Thanh Cong" <notifications@github.com>写道：

**Comment by ptcong** [comment]
Ok, i made new commit for this
